#!/bin/sh
set -x   # all executed commands are printed to the terminal

echo "Start to build and test locally before pushing"
./gradlew clean build test

# store the last exit code in a variable, 0 is success
RESULT=$?
exit $RESULT # non-zero code will prevent the push
