#!/bin/sh
set -x   # all executed commands are printed to the terminal

echo "Start to build and test locally before pushing"
./gradlew clean build test jacocoTestCoverageVerification

# store the last exit code in a variable, 0 is success
RESULT=$?

if [ $RESULT -eq 0 ]; then
    ./gradlew updateMinimumCoverage
    git add ./gradle/config.properties
    git commit -m "Auto update minimum test coverage limit"
    git fetch origin
    git push --no-verify
fi

exit $RESULT # non-zero code will prevent the push
